<a href="https://colab.research.google.com/github/VarunSuddala/AIML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy--array


In [2]:
import numpy as np

In [3]:
np_array = np.array([1,2,3,5])
print(np_array)
print(type(np_array))
print(np_array.dtype)

[1 2 3 5]
<class 'numpy.ndarray'>
int64


In [4]:
#example 1
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# example-3 [array containing Stings]
arr=np.array(["apple","banana","cherry"])
print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U6


In [7]:
#compression between python list and python array
from time import time
import numpy as np
size=10_000_000
python_list=list(range(size))
start=time()
list_sq=[x**2 for x in python_list]
end=time()
print("time taken by python list",f"{end-start:.2f} ")

numpy_array=np.array(range(size))
start=time()
numpy_array_sq=numpy_array**2
end=time()
print("time taken by numpy array",f"{end-start:.2f}")

time taken by python list 0.72 
time taken by numpy array 0.02


In [8]:
arr1=np.zeros((5,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
arr1=np.ones((5,5))
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
arr1=np.full((5,5),5)
arr2=np.full((5),6)
print(arr1)
print()
print(arr2)
print()

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]

[6 6 6 6 6]



In [11]:
arr1=np.eye(5)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
arr1=np.arange(1,20,2)
print(arr1)
arr1=np.arange(0,20,2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]


##  **operations on arrays**

In [13]:
#Basic Arithmetic Operations
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(f"addition {arr1+arr2}") #addition
print(f"subtraction {arr1-arr2}") #subtraction
print(arr1*arr2) #multiplication
print(arr1/arr2) #division
print(arr1%arr2) #modulus

addition [ 6  8 10 12]
subtraction [-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]


In [14]:
#Statistical & Aggregation Operations
arr1=np.array([1,2,3,4])
print(f"sum {np.sum(arr1)}") #sum
print(f"mean {np.mean(arr1)}") #mean
print(f"median {np.median(arr1)}") #median


sum 10
mean 2.5
median 2.5


In [15]:
#Manipulation & Reshaping
arr1=np.array([1,2,3,4,5,6])
print(arr1.shape)
arr1=(arr1.reshape(2,3))
print(arr1)
print(arr1.flatten())
print()
print(arr1.T)
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10])
print(np.concatenate((arr1,arr2)))

(6,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[1 4]
 [2 5]
 [3 6]]
[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
    #Comparison & Logical Operations
    print(arr2>[arr2>5])
    print(arr2[arr2==5])
    # The original error was here: arr1=np.where(arr > 0, 1, 0)
    # 'arr' was a string array, so 'arr > 0' caused a UFuncTypeError.
    # Using 'arr2' which is a numerical array for this operation.
    arr1=np.where(arr2 > 0, 1, 0)
    print(f"Result of np.where on arr2: {arr1}")

[[ True  True  True  True]]
[]
Result of np.where on arr2: [1 1 1 1]


In [17]:
arr2=np.array([0,45,90,120,180])
print(np.sin(arr2))
print(np.cos(arr2))
print(np.tan(arr2))

[ 0.          0.85090352  0.89399666  0.58061118 -0.80115264]
[ 1.          0.52532199 -0.44807362  0.81418097 -0.59846007]
[ 0.          1.61977519 -1.99520041  0.71312301  1.33869021]


In [18]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60,10])

print(arr[1:4])   # [20, 30, 40] (from index 1 to 3)
print(arr[:3])    # [10, 20, 30] (beginning to index 2)
print(arr[::2])   # [10, 30, 50] (every second element)
print(arr[::-1])  # [60, 50, 40, 30, 20, 10] (reversed)


[20 30 40]
[10 20 30]
[10 30 50 10]
[10 60 50 40 30 20 10]


In [19]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Get the first two rows and last two columns
print(matrix[:2, 1:])
# Output:
# [[2, 3],
#  [5, 6]]

# Get the entire second column
print(matrix[:, 1]) # [2, 5, 8]

[[2 3]
 [5 6]]
[2 5 8]


In [20]:
mask=arr>20
print(arr[mask])


[30 40 50 60]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx])

[1 2 5]


In [22]:
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] # [2, 3, 4]
copy_list[1] = 333
print(copy_list)
print(py_list) # [1, 2, 3, 4, 5] - remains same
# Sliced Array is a VIEW
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] # [2, 3, 4]
view_arr[1] = 333
print(view_arr)
print(np_arr) # [1, 2, 333, 4, 5] - changes
# Creating a COPY for Array
copy_arr = np_arr[1:4].copy() # [2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr) # [1, 2, 3, 4, 5] - remains same

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [23]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(arr2D)) # sum of entire array - 45
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns) # [12 15 18]
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows) # [6 15 24]
# Slicing
print(arr2D[0:3, 1:3]) # slice rows(0, 1, 2) x cols(1, 2)
# [[2 3]
# [5 6]
# [8 9]]


45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [24]:
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])
print(arr3D, arr3D.shape)
# Indexing
print(arr3D[0][1][1]) # 4
print(arr3D[1][2][1]) # 12
print(arr3D[:, :, 0]) # first col from both layers
print(arr3D[:, 0, :]) # first row from both layers
# Manipulating data
arr3D[:, 0, :] = 99 # change first row to store 99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])
print(arr.dtype) # int64
print(arr2.dtype) # float64
print(arr3.dtype) # U
# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)
# Objects
arr = np.array (["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

int64
float64
<U5
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [28]:
arr = np.array([1, 2, 3, 4, 5]) # Ensure 'arr' is a numerical array for this demonstration
# Changing the data type
new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)
new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)

[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64


**Vectorization**

In [30]:
rr = np.array([1, 2, 3, 4, 5])
sq_arr = arr ** 2 # Square of all nums
print(sq_arr)
arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2) # Sum of 2 arrays

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [31]:
# Standard Vector Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(normalized_arr)
# Column wise Normalization
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr - mean) / std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr)) # 15
print(np.prod(arr)) # 120
print(np.min(arr)) # 1
print(np.argmin(arr)) # 0
print(np.max(arr)) # 5
print(np.argmax(arr)) # 4
print(np.mean(arr)) # 3.0
print(np.median(arr)) # 3.0
print(np.std(arr)) # 1.41
print(np.var(arr)) # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0
